-- Schema base: tabelas principais criadas fora do sistema de migrations.
-- Todas com IF NOT EXISTS para ser seguro em deploy novo ou existente.

-- ===== 1. selecoes =====
CREATE TABLE IF NOT EXISTS public.selecoes (
  id           BIGINT PRIMARY KEY,
  nome         TEXT,
  bandeira_url TEXT
);

ALTER TABLE public.selecoes ENABLE ROW LEVEL SECURITY;

-- ===== 2. jogadores =====
CREATE TABLE IF NOT EXISTS public.jogadores (
  id_sofascore  BIGINT PRIMARY KEY,
  nome_completo TEXT,
  nome_fantasia TEXT,
  posicao       TEXT,
  preco         NUMERIC,
  selecao_id    BIGINT REFERENCES public.selecoes(id),
  status_medico TEXT DEFAULT 'disponivel',
  foto_url      TEXT
);

ALTER TABLE public.jogadores ENABLE ROW LEVEL SECURITY;

-- ===== 3. times_usuarios =====
CREATE TABLE IF NOT EXISTS public.times_usuarios (
  id                               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  usuario_id                       UUID NOT NULL REFERENCES auth.users(id),
  nome_time                        TEXT NOT NULL DEFAULT 'Meu Time',
  banco_cartoletas                 NUMERIC NOT NULL DEFAULT 150.0,
  transferencias_usadas_rodada     INT NOT NULL DEFAULT 0,
  penalidade_transferencias_rodada NUMERIC(8,2) NOT NULL DEFAULT 0.00,
  created_at                       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.times_usuarios ENABLE ROW LEVEL SECURITY;

-- ===== 4. elencos_usuarios =====
CREATE TABLE IF NOT EXISTS public.elencos_usuarios (
  time_usuario_id BIGINT NOT NULL REFERENCES public.times_usuarios(id) ON DELETE CASCADE,
  jogador_id      BIGINT NOT NULL REFERENCES public.jogadores(id_sofascore),
  eh_capitao      BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (time_usuario_id, jogador_id)
);

ALTER TABLE public.elencos_usuarios ENABLE ROW LEVEL SECURITY;
